replicaCount: 1

image:
  repository: ghcr.io/sva73/backend
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 8080

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: traefik
  host: api.local

livenessProbe:
  path: /
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 2

readinessProbe:
  path: /
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 2