apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-service-account
  namespace: backend

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: workers
  name: pod-manager-role
rules:
- apiGroups: ["", "batch"]
  resources: ["pods", "jobs"]
  verbs: ["create", "get", "list", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-manager-binding
  namespace: workers
subjects:
- kind: ServiceAccount
  name: backend-service-account
  namespace: backend
roleRef:
  kind: Role
  name: pod-manager-role
  apiGroup: rbac.authorization.k8s.io