apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: backend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: myapp.test
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: fastapi-backend-service
            port:
              number: 8000